# Generated by Django 6.1.1 on 2026-09-21 21:58

from django.db import migrations, models


def normalizar_tipo_acervo(apps, schema_editor):
    Livro = apps.get_model('acervo', 'Livro')
    Livro.objects.using(schema_editor.connection.alias).filter(
        tipo_acervo__in=['físico', '', '1'],
    ).update(tipo_acervo='fisico')


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_livro_categoria_livro_tipo_acervo'),
    ]

    operations = [
        migrations.RunPython(normalizar_tipo_acervo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='livro',
            name='tipo_acervo',
            field=models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], default='fisico', max_length=10),
        ),
    ]
